### ISSUE TITLE
Multiple UAVs in One Simulation Environment

### ISSUE THREAD

**Issue by mustafagokce09** [SwiftGust/ardupilot_gazebo#13]
Hi.
How can i simulate multiple copter of plane in one simulation environment?
In SITL part i can do this:
```
sim_vehicle.py -v ArduPlane -f gazebo-zephyr -I0
sim_vehicle.py -v ArduPlane -f gazebo-zephyr -I1
```
What should i do in the world file?
Thanks...

**Comment by SwiftGust** [comment]
Look closely here https://github.com/SwiftGust/ardupilot_gazebo#multi-vehicle-simulation

You need world with multiple zephyr with different port connection, 
overwrite connection settings in the world or models 
https://github.com/SwiftGust/ardupilot_gazebo/blob/master/models/zephyr_delta_wing_ardupilot_demo/delta_wing.sdf#L134-L135

**Comment by mustafagokce09** [comment]
I do not know whats happening but i created two models as `zephyr_delta_wing_ardupilot_1 ` and `zephyr_delta_wing_ardupilot_2` and also i changed their SYSIDs as 1 and 2. But for some time the second uav becomes unstable and it crashes. 
As you can see on the image i am loading same waypoints to them (takeoff and RTL) but second uav as you can see after the takeoff becomes unstable.
![Screenshot from 2019-03-21 11-22-50](https://user-images.githubusercontent.com/15967032/54740269-e2619100-4bcb-11e9-9218-ce39a3a2d45e.png)
