### ISSUE TITLE
Arducopter crashes regularly

### ISSUE THREAD

**Issue by rishab26201** [SwiftGust/ardupilot_gazebo#16]
Hey,
So I arm and take off the drone. But it goes above the given setpoint and crashes. Even if it doesn't it keeps oscillating (+/-2 m) and is very unstable. Is there any way to correct this. Also for thrust input of 0.5 from setpoint_raw/attitude the drone moves sideways even though I dont give roll or yaw. Is there any way to correct this

**Comment by SwiftGust** [comment]
Hello I don't know what you are trying to do.
It looks like what you are doing is kinda MAVROS node to control drone in guided mode
Have you checked drone not working only with ArduPilot? (i.e. poshold, guided, auto etc...) 

It is natural drone goes sideways if you gave only throttle command.
What makes you think that 50% of throttle make the drone hover?

What you are doing is nothing different that doing stabilize mode with rc transmitter, not even althold mode. 
If you want to hover your drone you should give velocity or position command, not attitude command.

When you using gazebo, you can't expect perfect, simulated drone from simple dynamics model like mostly seen in MATLAB/Simulink.
