### ISSUE TITLE
Standard VTOL SITL Gazebo9

### ISSUE THREAD

**Issue by LightningPORTO** [SwiftGust/ardupilot_gazebo#18]
Hi there, 

Im trying to use the ardupilot_gazebo plugin from this repo and having no success.

On master there is a model called "standard_vtol" , and when I download the master branch, when compiling the "cmake -j4 " several erros apear. The solution is "git checkout gazebo9" witch forces me to use the gazebo9 branch.

On the gazebo9 branch, there is no "standard_vtol" model, so I have added the one from master.

After all of this, when trying to use SITL simulation with ardupilot and gazebo, with the commands:

For ardupilot:

sim_vehicle.py -v ArduPlane -f quadplane  -m --mav10 --map --console -I0

For gazebo, I have created one new world where I spawn the standard_vtol frame and type this on the command line:

gazebo --verbose vtol.world

The world was created by copying the "iris_ardupilot.world" and replacing on the last lines for standard_vtol when necessary.

Now, the problem:

- Both ardupilot console and QGroundControl recognize the commands and everything is working
- Gazebo launches the correct world and model.

However, the model does not move anything, like there is no link between ardupilot and gazebo.
Can anyone help on that? 

Thanks :)

-----------------------------------------------
CONSOLE MESSAGE FROM GAZEBO LAUNCH
-----------------------------------------------
Gazebo multi-robot simulator, version 9.11.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
Gazebo multi-robot simulator, version 9.11.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.18.131.46
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.18.131.46
[Msg] Home latitude is set to 41.186098.
[Msg] Home longitude is set to -8.705933.
[Msg] Home altitude is set to 3.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::rotor_0_joint] found for channel[0] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::rotor_1_joint] found for channel[1] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::rotor_2_joint] found for channel[2] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::rotor_3_joint] found for channel[3] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::rotor_puller_joint] found for channel[4] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::left_elevon_joint] found for channel[5] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::right_elevon_joint] found for channel[6] joint control active for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:129] joint [standard_vtol::elevator_joint] found for channel[7] joint control active for this channel.
[Msg] Connecting to PX4 SITL using UDP
[Msg] Lockstep is disabled
[Msg] Using MAVLink protocol v2.0
[Err] [InsertModelWidget.cc:433] Missing model.config for model "/home/rui/ardupilot_gazebo/gazebo_models/.hg"
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/user_camera/pose, deleting message. This warning is printed only once.

-----------------------------------------------
My own vtol.world file
-----------------------------------------------

<sdf version="1.6">
  <world name="default">
    <physics type="ode">
      <ode>
        <solver>
          <type>quick</type>
          <iters>100</iters>
          <sor>1.0</sor>
        </solver>
        <constraints>
          <cfm>0.0</cfm>
          <erp>0.9</erp>
          <contact_max_correcting_vel>0.1</contact_max_correcting_vel>
          <contact_surface_layer>0.0</contact_surface_layer>
        </constraints>
      </ode>
      <real_time_update_rate>0</real_time_update_rate>
      <max_step_size>0.0025</max_step_size>
    </physics>

      <include>
      <uri>model://sun</uri>
    </include>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>5000 5000</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>1</mu>
                <mu2>1</mu2>
              </ode>
            </friction>
          </surface>
        </collision>
        <visual name="runway">
          <pose>000 0 0.005 0 0 -1.5707</pose>
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>1829 45</size>
            </plane>
          </geometry>
          <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Runway</name>
            </script>
          </material>
        </visual>

        <visual name="grass">
          <pose>0 0 -0.1 0 0 0</pose>
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>5000 5000</size>
            </plane>
          </geometry>
          <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Grass</name>
            </script>
          </material>
        </visual>

      </link>
    </model>

    <model name="standard_vtol">
      <pose> 0 0 0 0 0 0 </pose>
      <include>
        <uri>model://standard_vtol</uri>
         <pose> 0 0 0 0 0 0 </pose>
      </include>
    </model>
  </world>
</sdf>

**Comment by SwiftGust** [comment]
Hi,
Currently, standard vtols, tailsitter, tiltrotor models are just copy of https://github.com/px4/sitl_gazebo
Those models are need to modified in plugin interfaces, need to replaceall the plugins with aerodynamic plugins (from gazebo), ardupilot plugin (from this repo).

> However, the model does not move anything, like there is no link between ardupilot and gazebo.

is exact in current status.
For now, you need to edit models to make it work, should replace px4-gazebo plugins with ardupilot-gazebo plugins

Also gazebo-9 branch can be merged in the master branch in the way that https://github.com/px4/sitl_gazebo did, but I'm not available.
