### ISSUE TITLE
How were the aerodynamic parameters for the Iris model obtained?

### ISSUE THREAD

**Issue by christopher-o-toole** [SwiftGust/ardupilot_gazebo#7]
```
      <a0>0.3</a0>
      <alpha_stall>1.4</alpha_stall>
      <cla>4.2500</cla>
      <cda>0.10</cda>
      <cma>0.00</cma>
      <cla_stall>-0.025</cla_stall>
      <cda_stall>0.0</cda_stall>
      <cma_stall>0.0</cma_stall>
      <area>0.002</area>
      <air_density>1.2041</air_density>
      <cp>0.084 0 0</cp>
      <forward>0 1 0</forward>
      <upward>0 0 1</upward>
```

I'm a member of a university team where we build our own drones from scratch, and our engineering team is stuck on how to calculate some of these coefficients. The parameters as specified by http://gazebosim.org/tutorials?tut=aerodynamics&cat=plugins seem to be better suited to a fixed-wing aircraft rather than a quadcopter.

**Comment by SwiftGust** [comment]
That aerodynamic coefficient is not I have modelled, you can find the author in config file.
Gazebo aerodynamics plugin does modelled aerodynamics as airfoil level that may not be easy to understand but every airfoil does apply the same principle.
Most of the technical papers do take much-simplified aerodynamics just to model hovering flight only.
Maybe you can find a simplified wrapper for multicopter in PX4 RotoRs.
https://github.com/PX4/sitl_gazebo

**Comment by SwiftGust** [comment]
Leave comment if there is more questions.
