### ISSUE TITLE
Iris gimbal mount

### ISSUE THREAD

**Issue by johnbdk** [SwiftGust/ardupilot_gazebo#8]
Hello,

In the model '**iris with standoffs demo**' sdf file, gimbal model should included as:
**0 -0.01 0.070 1.57 0 1.57** and not as **0 -0.01 0.070 1.57 0 -1.57**. Otherwise the
frames of the camera are in a contrary way with respect of the head of the drone.

**Comment by SwiftGust** [comment]
That gimbal is the actually lazy model for precision landing,
not to modify parameter inside ArduCopter.
If you want to rotate yaw around 180 degrees, then you should make an appropriate change accordingly.
